### ISSUE TITLE
Loops should allow more than one run call

### ISSUE THREAD

**Issue by joaquimrocha** [ldo/glibcoro#1]
Hello, I have been using glibcoro, and found that there seems to be a discrepancy between what this implementation does and what the Python docs mention, in the case of calling `run_until_complete` or `run_forever`:

> If stop() is called while run_forever() is running, the loop will run the current batch of callbacks and then exit. Note that new callbacks scheduled by callbacks will not run in this case; instead, they will run the next time run_forever() or run_until_complete() is called.

Is my assumption that glibcoro should allow such calls more than once?
I guess that allowing this means the `GLib.MainLoop` used should be replaced by a new instance if it's been quit. Are there implications in this case for multithreaded programs we should account for?

Let me know what you think about all this. And thanks for doing this GLib based implementation.

**Comment by ldo** [comment]
I would like to be as compatible with standard `asyncio` behaviour as I can manage. I think I could deal with this by not allocating the `_gloop` value until one of the `run` calls is made, and then getting rid of it after the run is over. The whole point of `asyncio` is to avoid multithreading, so I don’t see that being a big issue.

**Comment by ldo** [comment]
OK, I have implemented the above change.
